export type User = {
    id: number;
    email: string;
    username: string;
    type: 'client' | 'consultant' | 'nutritionist';
    age?: number;
    gender?: string;
    height?: number;
    weight?: number;
    activity?: string;
    metabolicRate?: number;
    city?: string;
    street?: string;
    zipCode?: string;
    phoneNumber?: string;
    blocked: boolean;
    confirmed?: boolean;
    provider?: string;
    createAt: string;
    updateAt: string;
};
