import "@/styles/global.css";
import React from "react";
import { Inter } from "next/font/google";
import { serverFetcher } from "@/lib/fetchers/serverFetcher";
import { User } from "@/types/User";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default async function RootLayout({
                                             children,
                                             modal,
                                             nutritionist,
                                             client
                                         }: {
    children: React.ReactNode;
    modal: React.ReactNode;
    nutritionist: React.ReactNode;
    client: React.ReactNode;
}) {
    // get current user type
    // @ts-ignore This endpoint is different from the others, has no `data` key :(
    const user = await serverFetcher<User>({ url: "/users/me", method: "get" }) as User;
    const userType = user?.type === "client" ? client : nutritionist;

    return (
        <html lang="en">
        <body className={`bg-white text-black ${inter.className}`}>
        {userType}
        {children}
        {modal}
        </body>
        </html>
    );
}

// data: {}, meta: {}
// {}
