export const mockExtendedIngredients = [
  {
    id: 8120,
    aisle: "Cereal",
    image: "rolled-oats.jpg",
    consistency: "SOLID",
    name: "oats",
    nameClean: "rolled oats",
    original: "2 cups Oats",
    originalName: "Oats",
    amount: 2.0,
    unit: "cups",
    meta: [],
    measures: {
      us: {
        amount: 2.0,
        unitShort: "cups",
        unitLong: "cups",
      },
      metric: {
        amount: 473.176,
        unitShort: "ml",
        unitLong: "milliliters",
      },
    },
  },
  {
    id: 19296,
    aisle: "Nut butters, Jams, and Honey",
    image: "honey.png",
    consistency: "LIQUID",
    name: "honey",
    nameClean: "honey",
    original: "1/3 cup Honey",
    originalName: "Honey",
    amount: 0.33333334,
    unit: "cup",
    meta: [],
    measures: {
      us: {
        amount: 0.333,
        unitShort: "cups",
        unitLong: "cups",
      },
      metric: {
        amount: 78.863,
        unitShort: "ml",
        unitLong: "milliliters",
      },
    },
  },
  {
    id: 9040,
    aisle: "Produce",
    image: "bananas.jpg",
    consistency: "SOLID",
    name: "bananas",
    nameClean: "banana",
    original: "2 Bananas, mashed",
    originalName: "Bananas, mashed",
    amount: 2.0,
    unit: "",
    meta: ["mashed"],
    measures: {
      us: {
        amount: 2.0,
        unitShort: "",
        unitLong: "",
      },
      metric: {
        amount: 2.0,
        unitShort: "",
        unitLong: "",
      },
    },
  },
  {
    id: 93607,
    aisle: "Milk, Eggs, Other Dairy",
    image: "almond-milk.png",
    consistency: "LIQUID",
    name: "almond milk",
    nameClean: "almond milk",
    original: "2 cups Almond Milk",
    originalName: "Almond Milk",
    amount: 2.0,
    unit: "cups",
    meta: [],
    measures: {
      us: {
        amount: 2.0,
        unitShort: "cups",
        unitLong: "cups",
      },
      metric: {
        amount: 473.176,
        unitShort: "ml",
        unitLong: "milliliters",
      },
    },
  },
  {
    id: 1124,
    aisle: "Milk, Eggs, Other Dairy",
    image: "egg-white.jpg",
    consistency: "SOLID",
    name: "egg whites",
    nameClean: "egg whites",
    original: "1/2 cup Egg Whites",
    originalName: "Egg Whites",
    amount: 0.5,
    unit: "cup",
    meta: [],
    measures: {
      us: {
        amount: 0.5,
        unitShort: "cups",
        unitLong: "cups",
      },
      metric: {
        amount: 118.294,
        unitShort: "ml",
        unitLong: "milliliters",
      },
    },
  },
  {
    id: 99239,
    aisle: "Health Foods",
    image: "plain-protein-powder.png",
    consistency: "SOLID",
    name: "protein powder",
    nameClean: "protein powder",
    original:
      "2 scoops of Protein Powder (I used Dymatize Elite Banana Flavour)",
    originalName: "Protein Powder (I used Dymatize Elite Banana Flavour)",
    amount: 2.0,
    unit: "scoops",
    meta: ["(I used Dymatize Elite Banana Flavour)"],
    measures: {
      us: {
        amount: 2.0,
        unitShort: "scoops",
        unitLong: "scoops",
      },
      metric: {
        amount: 2.0,
        unitShort: "scoops",
        unitLong: "scoops",
      },
    },
  },
  {
    id: 18371,
    aisle: "Baking",
    image: "white-powder.jpg",
    consistency: "SOLID",
    name: "baking powder",
    nameClean: "low sodium baking powder",
    original: "1 tsp Baking Powder",
    originalName: "Baking Powder",
    amount: 1.0,
    unit: "tsp",
    meta: [],
    measures: {
      us: {
        amount: 1.0,
        unitShort: "tsp",
        unitLong: "teaspoon",
      },
      metric: {
        amount: 1.0,
        unitShort: "tsp",
        unitLong: "teaspoon",
      },
    },
  },
  {
    id: 2010,
    aisle: "Spices and Seasonings",
    image: "cinnamon.jpg",
    consistency: "SOLID",
    name: "cinnamon",
    nameClean: "cinnamon",
    original: "2 tsp Cinnamon",
    originalName: "Cinnamon",
    amount: 2.0,
    unit: "tsp",
    meta: [],
    measures: {
      us: {
        amount: 2.0,
        unitShort: "tsps",
        unitLong: "teaspoons",
      },
      metric: {
        amount: 2.0,
        unitShort: "tsps",
        unitLong: "teaspoons",
      },
    },
  },
  {
    id: 4047,
    aisle: "Health Foods;Baking",
    image: "oil-coconut.jpg",
    consistency: "LIQUID",
    name: "coconut oil",
    nameClean: "coconut oil",
    original: "1 tsp Coconut Oil",
    originalName: "Coconut Oil",
    amount: 1.0,
    unit: "tsp",
    meta: [],
    measures: {
      us: {
        amount: 1.0,
        unitShort: "tsp",
        unitLong: "teaspoon",
      },
      metric: {
        amount: 1.0,
        unitShort: "tsp",
        unitLong: "teaspoon",
      },
    },
  },
  {
    id: 2050,
    aisle: "Baking",
    image: "vanilla-extract.jpg",
    consistency: "LIQUID",
    name: "vanilla extract",
    nameClean: "vanilla extract",
    original: "1 tsp Vanilla Extract",
    originalName: "Vanilla Extract",
    amount: 1.0,
    unit: "tsp",
    meta: [],
    measures: {
      us: {
        amount: 1.0,
        unitShort: "tsp",
        unitLong: "teaspoon",
      },
      metric: {
        amount: 1.0,
        unitShort: "tsp",
        unitLong: "teaspoon",
      },
    },
  },
  {
    id: 12155,
    aisle: "Nuts;Baking",
    image: "walnuts.jpg",
    consistency: "SOLID",
    name: "walnuts",
    nameClean: "walnuts",
    original: "1/4 cup Walnuts",
    originalName: "Walnuts",
    amount: 0.25,
    unit: "cup",
    meta: [],
    measures: {
      us: {
        amount: 0.25,
        unitShort: "cups",
        unitLong: "cups",
      },
      metric: {
        amount: 59.147,
        unitShort: "ml",
        unitLong: "milliliters",
      },
    },
  },
  {
    id: 9299,
    aisle: "Dried Fruits;Produce;Baking",
    image: "raisins.jpg",
    consistency: "SOLID",
    name: "raisins",
    nameClean: "raisins",
    original: "1/2 cup Raisins",
    originalName: "Raisins",
    amount: 0.5,
    unit: "cup",
    meta: [],
    measures: {
      us: {
        amount: 0.5,
        unitShort: "cups",
        unitLong: "cups",
      },
      metric: {
        amount: 118.294,
        unitShort: "ml",
        unitLong: "milliliters",
      },
    },
  },
];
